### ISSUE TITLE
Features(ASVs) found in negative controls only not identified as contaminants

### ISSUE THREAD

**Issue by ibrila** [benjjneb/decontam#100]
Hi,

I'm using `decontam` on 16S data. I used the raw ASV table in `decontam` and the assignment of samples to groups "sample" and "control". I have 376 samples and 16 negative controls. 

I was able to identify 345 contaminating sequences (out of a total of 5111), however, upon further inspection, I noticed that a lot of ASVs found only in negative controls are not marked as contaminants.  I had  134 such ASVs with frequency in negative controls from 10 to 602.

Why could such an issue arise and how to fix it?

Code used:

`contaminants <- isContaminant(seqtab = otus, neg = neg, method="prevalence")`

Thanks!

**Comment by ibrila** [comment]
A further issue I noticed is features marked as contaminants, although they appear much much more frequently in samples when compared to the negative controls, for example, feature A appears 458 times in controls and 30208 times in samples but is marked as a contaminant by `decontam`.

**Comment by benjjneb** [comment]
> I noticed that a lot of ASVs found only in negative controls are not marked as contaminants. I had 134 such ASVs with frequency in negative controls from 10 to 602. Why could such an issue arise and how to fix it?

On default settings, `decontam` will not call anything a contaminant that only appears on 1 sample. My guess is that explains most if not all of these ASVs.

> A further issue I noticed is features marked as contaminants, although they appear much much more frequently in samples when compared to the negative controls, for example, feature A appears 458 times in controls and 30208 times in samples but is marked as a contaminant by decontam.

First, you are using the "prevalence" method. Thus, no abundance information is used, only presnce/absence information is being used by that method.

Second, the discrepancy you described, a ratio of 30208/458 ~ 60x more abundance in real samples than controls, is comparable to the 376/16 ~ 25x ratio of real samples to control samples, and often real samples also have more reads. Thus, the fraction of control and real samples that have that ASV are probably similar, in which case decontam under default settings might conservatively _not_ classify the ASV a a contaminant.

The decontam paper describes in more detail how the method works and the ideas behind it: https://doi.org/10.1186/s40168-018-0605-2

**Comment by ibrila** [comment]
This has been very helpful, thanks a lot!
