### ISSUE TITLE
Proposal - hierarchical approach

### ISSUE THREAD

**Issue by andrewjmc** [benjjneb/decontam#104]
I love Decontam and have found it really useful (e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7523627). I also love treeclimbR and the ability to take a hierarchical approach to statistical tests in a taxonomy.

At the moment it's not possible to fuse the two (and allow contamination identification at different levels of a taxonomy in a data-dependent manner) because the statistics of Decontam produce (effectively) one-sided p values (as far as I can tell), and the author of treeclimbR does not recommend integrating this https://github.com/fionarhuang/treeclimbR/issues/15.

Can you conceive of a way of tweaking the statistical testing of Decontam such that p values were two-sided - e.g. negative vs positive associations with biomass?

Alternatively, has anyone considered some sort of stepwise hierarchical approach? E.g. Decontam could be applied from higher to lower levels of the taxonomy (perhaps with more stringent p value thresholds at higher levels of the taxonomy) or the reverse perhaps selecting higher levels of the taxonomy based on nodes' p values and also the proportion (by number or relative abundance) of child species which are contaminants.

**Comment by benjjneb** [comment]
Thanks for these suggestions. A couple thoughts:

> Can you conceive of a way of tweaking the statistical testing of Decontam such that p values were two-sided - e.g. negative vs positive associations with biomass?

For the frequency method in decontam (the method using input biomass estimates), I don't think it makes sense to try to develop a two-sided p-value. First off, the frequency method is not really producing a p-value. It is performing a model comparison between a contaminant model (log-slope = -1) and a non-contaminant model (log-slope = 0), and generating a score that indicates which model is more consistent with the data (~0: contaminant, ~1: non-contaminat). This borrows a statistical testing procedure, but it does not produce true p-values, that is there is no real guarantee on the false positive rate.

> Alternatively, has anyone considered some sort of stepwise hierarchical approach? E.g. Decontam could be applied from higher to lower levels of the taxonomy (perhaps with more stringent p value thresholds at higher levels of the taxonomy) or the reverse perhaps selecting higher levels of the taxonomy based on nodes' p values and also the proportion (by number or relative abundance) of child species which are contaminants.

This is interesting, but the devil is likely in the details, and I do not know of anyone who has proposed or worked on something like this. We don't have any current project like this.

**Comment by andrewjmc** [comment]
Thanks for the response!
