### ISSUE TITLE
How to get the taxa names of contaminants

### ISSUE THREAD

**Issue by kbcn** [benjjneb/decontam#11]
I'm new to both dada2 and decontam, and am planning to implement a pipeline using both of these within my lab.

I followed the dada2 pipeline tutorial (1.4) through the creation of a phyloseq object, and then using the decontam package. I used my own pretty typical 16s paired-end data set for this and slightly modified the parameters, but kept the workflow and functions the same. I also used the silva database.

Following decontam, when I view the "df.pres" table created at the end, this reports back to me the actual sequences and not assigned taxonomy. I tried tax_table(ps) on my phyloseq object, and it returned back a large output of lists of sequence data and not taxa names, and not the "Taxonomy table" format I'd expect from a phyloseq object. So I'm guessing the problem may actually be upstream in my dada2 analysis? I wasn't sure whether to post this here or in the dada2 issuetracker.

Any help you can provide would be so appreciated, as I'm stuck.

**Comment by benjjneb** [comment]
You should be able to get the dada2/base-R taxonomy table matrix back from phyloseq with the following:

```
tax <- as(tax_table(ps), "matrix")
```

Assuming that works, you can pull out the taxonomic assignments of the flagged contaminants pretty easily, as the `tax` object should have rownames that are the sequence variants:

```
tax[contam.sqs,]
unname(tax[contam.sqs,])
```

Use `unname` to drop the long rownames if inspecting the standard output.

**Comment by kbcn** [comment]
That worked, thank you! 

So it is "correct" then if I input (for example):

`tax_table(phyloseq_obj)[1,1]`

my output is:

`Kingdom
(insert V4 sequence) "Bacteria"`

This is the case for each taxonomic assignment through genus or species - the sequence itself is included in the output, rather than what I had (perhaps mistakenly) expected, something like:

`Kingdom
(some number) Bacteria`

I can move this part of the question to the dada2 issue tracker if you think that would be more appropriate. I greatly appreciate your help!

**Comment by benjjneb** [comment]
Really this is a phyloseq question, as what you are asking about is the specific way in which the `taxonomyTable` class defined in phyloseq is printed to the screen.

The value of `tax_table(phyloseq_obj)[1,1]` is "Bacteria".
The column name of `tax_table(phyloseq_obj)[1,1]` is "Kingdom".
The row names of `tax_table(phyloseq_obj)[1,1]` is (insert V4 sequences).

And it all gets printed to the screen in the way you are seeing.
