### ISSUE TITLE
Controls Removal prior to filtering contaminants using 'frequency'

### ISSUE THREAD

**Issue by andrebolerbarros** [benjjneb/decontam#113]
Hi Benjamin,

This is more a technical question than issue with the code. I have some 16s data from mice cohoused vs single-housed, extracted in two different runs (each one with its own control). After all the pre-processing, I am now starting to do the 'decontam' step of my pipeline.

After running all the samples with the 'frequency' mode, I get 9 contaminants. As the tutorial recommends, I plotted the taxa and I get the following: 

![image](https://user-images.githubusercontent.com/16413257/174804381-a621dfee-5fda-4630-8304-3fcd84031e61.png)

Now, as you can see, I think most of these contaminants are being identified or tagged as such because of one outlier sample. I used the data produced for this plot to then plot the points but, now with colors for conditions (I wasn't able to do it in 'plot_frequency'). The result is the following:
![image](https://user-images.githubusercontent.com/16413257/174804684-db54e006-f345-4dbc-b71e-463b1ca1ce94.png)

It seems the outlier that is causing this to be considered problematic are the negative controls (or at least, one of them). Therefore, I think we should exclude the negative controls prior to 'decontam', since the results seem to be biased. Would you agree?

Thanks in advance,

André

**Comment by andrebolerbarros** [comment]
Just letting here the code used to analyse and plot these:

```
contamdf.freq <- isContaminant(ps1, method="frequency", conc="DNA_quant")
head(contamdf.freq)

table(contamdf.freq$contaminant)

contams<-rownames(contamdf.freq)[contamdf.freq$contaminant==T]

freq_col<-plot_frequency(ps1,taxa_names(ps1)[taxa_names(ps1) %in% contams], conc="DNA_quant")+
  xlab("DNA Concentration")

freq_col

ggplot(data=freq_col$data,aes(x=DNA_conc,y=taxon_abundance,colour=Housing))+
  geom_point(size=3)+
  facet_wrap(~taxa,scales="free_y")

```

**Comment by benjjneb** [comment]
> It seems the outlier that is causing this to be considered problematic are the negative controls (or at least, one of them). Therefore, I think we should exclude the negative controls prior to 'decontam', since the results seem to be biased. Would you agree?

Yes, for the frequency method. From the paper: 

> The assumptions of decontam, especially the frequency method, can be violated if bacterial biomass systematically differs between groups of samples. For example, if decontam were applied to a mixed set of stool (high biomass) and airway (low biomass) samples, real sequences in the airway samples could be classified as contaminants, because they have a higher frequency in the low-concentration samples. Therefore, we recommend applying decontam independently to samples collected from different environments.

The negative control sample can be thought of, in this context, as an extremely different environment.

Note that this behavior of separating out the negative controls before applying the frequency method is done automatically when running decontam in the "combined" modes, that use both the prevalence and frequency methods together.

**Comment by andrebolerbarros** [comment]
Thanks Benjamin!

The problem, as I already discussed with you (Issue #38) is that I can only have one control per extraction run, so the prevalence method is not recommended for my samples. But thanks for the suggestion!
