### ISSUE TITLE
Export data from prevalent option

### ISSUE THREAD

**Issue by K-Gutierrez** [benjjneb/decontam#119]
Hi, this is an excellent program for checking contamination in amplicon sequencing samples. I am new in R, so I am following this tutorial: https://benjjneb.github.io/decontam/vignettes/decontam_intro.html#putting-it-all-together

I have two questions:

1) How can I remove the contaminants using the prevalence option, I am looking for a similar command such as you wrote in the Frequency section: 

$ps
## tax_table()   Taxonomy Table:    [ 1951 taxa by 6 taxonomic ranks ]

$ps.noncontam <- prune_taxa(!contamdf.freq$contaminant, ps)
ps.noncontam

## tax_table()   Taxonomy Table:    [ 1893 taxa by 6 taxonomic ranks ]

2) I would like to use the combined method. What is the command that I need to run?

Thanks in advance.

**Comment by benjjneb** [comment]
On (1), You would use the same command to remove the taxa idenfied as contaminants, whatever methods you are using. All of them create a TRUE/FALSE vector in the `$contaminant` column of the returned data.frame that indicates the classified contaminants.

On (2), just set `isContaminant(..., method="combined")`. You'll also need to provide both the `conc` and `neg` arguments to the function as well (see the argument descriptions in `?isContaminant`).

**Comment by K-Gutierrez** [comment]
Awesome! thanks so much for your answer :)
