### ISSUE TITLE
Probable bug in "getFromPS(ps, conc) : ng.DNA is not a valid sample-variable in the provided phyloseq object."

### ISSUE THREAD

**Issue by roey-angel** [benjjneb/decontam#128]
After updating to version 1.20.0:
`isContaminant(Ps_obj, method = "frequency", conc = "ng.DNA")`
says:
```
Error in getFromPS(ps, conc) : 
  ng.DNA is not a valid sample-variable in the provided phyloseq object.
```
But 
```
isContaminant(Ps_obj, method = "frequency", conc = get_variable(Ps_obj, "ng.DNA"))
```
Works

**Comment by benjjneb** [comment]
What version of phyloseq are you using?
Can you provide a small phyloseq object that I can use to reproduce this behavior?

**Comment by roey-angel** [comment]
I'm using phyloseq 1.44
The issue turned out to be simply NAs in the "conc" variable.
The error message could be more informative, but it's nothing critical.
