### ISSUE TITLE
extraction control, pcr control and "buffer" control

### ISSUE THREAD

**Issue by doloacu** [benjjneb/decontam#129]
hello everyone, I have the need to add a different "blank" to the iso_blank and pcr_blank. Some of my samples were kept in a buffer. This was aliquoted and extracted in a different extraction series than my samples. So I would like to use decontam with iso_blank, pcr_blank and also add the "buffer_blank" variable. I would need help to do this.

Thank you so much
Dolo

**Comment by benjjneb** [comment]
All negative controls are not equal. The best negative controls are those that go through the entire extraction/library-prep/sequencing process. For example, a negative swab control where a swab is removed from its packaging in the environment of interest, but not used to swab anything, and then goes through the full workflow to produce a sequenced library.

Generated more of those types of controls, and don't bother with the intermediate controls that don't capture all the contaminants unless you are specifically doing workflow optimization.
