### ISSUE TITLE
Prevalence mode pruning

### ISSUE THREAD

**Issue by kose-bioinfo** [benjjneb/decontam#138]
Hi there,

I have 28 samples which include 3 neg control samples. I've followed the introductory vignette in prevalence mode and have the following outputs:

```
> table(contamdf.prev$contaminant)

FALSE  TRUE 
16928     2 
> head(which(contamdf.prev$contaminant))
[1]  3658 13462
> contamdf.prev05 <- isContaminant(ps, method="prevalence", neg="is.neg", threshold=0.5)
> table(contamdf.prev05$contaminant)

FALSE  TRUE 
16831    99 
```

I have pruned and plotted these as per:

Make phyloseq object of presence-absence in negative controls and true samples

```
ps.pa <- transform_sample_counts(ps, function(abund) 1*(abund>0))
ps.pa.neg <- prune_samples(sample_data(ps.pa)$Sample_or_Control == "CONTROL", ps.pa)
ps.pa.pos <- prune_samples(sample_data(ps.pa)$Sample_or_Control == "SAMPLE", ps.pa)
```

Make data.frame of prevalence in positive and negative samples

```
df.pa <- data.frame(pa.pos=taxa_sums(ps.pa.pos), pa.neg=taxa_sums(ps.pa.neg),
                    contaminant=contamdf.prev$contaminant)
ggplot(data=df.pa, aes(x=pa.neg, y=pa.pos, color=contaminant)) + geom_point() +
  xlab("Prevalence (Negative Controls)") + ylab("Prevalence (True Samples)")
```

Is the 'ps.pa.pos' phyloseq object now the object with the contaminants removed? or is another step involved before I can go on to plotting alpha and beta diversities etc.? 

When I check the number of taxa in ps.pa.pos and ps.pa.neg they are the same (16930) 

What is the method to remove all contaminants?

**Comment by benjjneb** [comment]
> Is the 'ps.pa.pos' phyloseq object now the object with the contaminants removed?

No, that is a phyloseq object that only includes non-control (or "positive") samples.
If you want to remove contaminant taxa, you need to use the analogous `prune_taxa` command.
`prune_samples` cuts down the number of samples in a phyloseq object.
`prune_taxa` cuts down the number of taxa in a phyloseq obejct, for example by removing those flagged as contaminants.

**Comment by kose-bioinfo** [comment]
Thank you, much appreciated.
