### ISSUE TITLE
Decontam error

### ISSUE THREAD

**Issue by OluchiAroh** [benjjneb/decontam#143]
Hi ,

I ran decontam using the code below : 

sample_data(ps)$is.neg <- sample_data(ps)$Type %in% c("Neg", "Pos")
contamdf.prev <- isContaminant(ps, method="prevalence", neg="is.neg")
table(contamdf.prev$contaminant)

and got this error: 

Error in if (any(rowSums(seqtab) == 0)) { : 
  missing value where TRUE/FALSE needed

Any idea what I might be doing wrong?

Thank you.

Phyloseq object details;
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 5694 taxa and 55 samples ]
sample_data() Sample Data:       [ 55 samples by 14 sample variables ]
tax_table()   Taxonomy Table:    [ 5694 taxa by 7 taxonomic ranks ]

**Comment by benjjneb** [comment]
Are there NAs in your `$is.neg` variable?

`summary(sample_data(ps)$is.neg)`

Or, are there NAs in the sequence table itself?

`summary(rowSums(otu_table(ps)))`

**Comment by OluchiAroh** [comment]
Hi,
 Thanks for the response. 

There are no NAs in the $is.neg variable but there are NAs in the sequence table itself.

> summary(rowSums(otu_table(ps)))
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
       0      529     1403    63138     4940 12473214     3562 

> summary(sample_data(ps)$is.neg)
   Mode   FALSE    TRUE 
logical      46       9

**Comment by benjjneb** [comment]
That's the issue then. How did NAs get into the sequence table? All the values there should be non-negative numerics.

**Comment by OluchiAroh** [comment]
I am not really sure. I imported a rds phyloseq object and I don't know how they created the file. I will look into it further.
