### ISSUE TITLE
Can i use "frequency" without DNA concentration?

### ISSUE THREAD

**Issue by kx11jkjk** [benjjneb/decontam#144]
Hello, thank you for your team's contribution to decontamination. 
I found some microbial cohort from the public database, but there is no negative control or DNA concentration information, is there any way to use your method for decontamination?
In the OTU table, rows are samples and columns are microbes. I am considering caculating the sum of each row to replace DNA concentration information for 'frequency' method. Is this method feasible? If it doesn't work, is there a better way?
Thanks for your help! Here is my data looks like:
             OTU1 OTU2  OTU3
sample1  0         3          1
sample2   2        5          45
sample3   1        0           0

**Comment by kx11jkjk** [comment]
![Snipaste_2024-03-04_00-48-49](https://github.com/benjjneb/decontam/assets/109641023/d56a1374-f36f-4d45-b4c5-639a123b4130)

**Comment by benjjneb** [comment]
> but there is no negative control or DNA concentration information, is there any way to use your method for decontamination?

No.

> I am considering caculating the sum of each row to replace DNA concentration information for 'frequency' method. Is this method feasible?

No. Read counts don't reflect input DNA concentrations, because libraries are mixed in varying ratios to try to get the same number of reads per sample.

**Comment by kx11jkjk** [comment]
thank you！

**Comment by kx11jkjk** [comment]
thank you！
