### ISSUE TITLE
Different results with same phyloseq

### ISSUE THREAD

**Issue by sfeds** [benjjneb/decontam#18]
This is maybe not and issue with the decontam, rather with phyloseq, but I've only found it out when using this package.

I've been testing a few parameters with my sequencing data, so I go and run DADA2 --> build phyloseq --> add metadata --> go to decontam script.

I went back and changed a couple of things in my metadata and did again build phyloseq with metadata --> go to decontam script.

And here I realized that although the results of the number of contaminants is constant, the "which" were different: (e.g.)
>table(contamdf.freq$contaminant)
#FALSE  TRUE 
#679     5 
>head(which(contamdf.freq$contaminant))
#[1]  72 168 271 447 533

And how I understood it, the "which" is ranked, right? so in this case would be the read at the 72nd abundance position... etc. So it is quite relevant information, that shouldn't change.

I then for the "fun of it" went and set.seed at the beginning of my build phyloseq script and then I get consistent results with the decontam... but I'm still puzzled as to why this would happen. Any ideas?

And sorry if it shouldn't go here.

**Comment by benjjneb** [comment]
That is weird but probably not important. Are the `taxa_names(ps)[which(contamdf.freq$contaminant)]` the same in each case?

My guess is that there is some reordering of the taxa that is happening when the phyloseq object is formed and that has some random element. But worth checking on.

Best place to ask this probably is the phyloseq forum though.

**Comment by sfeds** [comment]
Ok, will do! Thanks for the tip, I'll check the taxa names
