### ISSUE TITLE
correcting prevalence for read mis-assignment 

### ISSUE THREAD

**Issue by nhoffman** [benjjneb/decontam#19]
As I’m sure you know, every experiment has some degree of cross-contamination between specimens, due to both contamination of template DNA and barcode mis-assignment. For this reason, uncorrected presence/absence of small numbers of reads is likely to over-estimate prevalence, particularly for any organism present in high abundance in one or more specimens. I wonder how sensitive decontam is to inflated prevalence estimates due to artifactual low-level read mis-assignment. And if it makes a difference in the prediction of contaminants, what is the most appropriate way to correct for this? The approach that we have been using is 1) to filter reads by index read quality to minimize barcode mis-assignment (see https://github.com/nhoffman/barcodecop - we do this step before dada2), and 2) to ignore dada2 sequence variants appearing in a specimen with a weight below some threshold (typically < 0.1%). 

Thanks!
Noah

**Comment by benjjneb** [comment]
This is a real problem, and seems to vary a lot between different sequencing instruments and protocols. We don't have a solution right now. Certainly open to any ideas people have.

That is very cool that you have put together some software to do the index-read filtering! At some point I asked @digitalwright if their was going to be a tool released implementing that strategy, but as I vaguely recall I don't think there was going to be.

I think the steps you describe make sense, although the per-sample frequency threshold is of course somewhat unsatisfying as in many environments we would like to be able to measure community members at those low frequencies.

**Comment by digitalwright** [comment]
Yes, I recall our discussion about this:
https://github.com/benjjneb/decontam/issues/9#issuecomment-357066503

**Comment by benjjneb** [comment]
Closing, but this method seems worth looking into for dual-indexed libraries: [Computational correction of index switching in multiplexed sequencing libraries](https://www.nature.com/articles/nmeth.4666)
