### ISSUE TITLE
Different kinds of negative controls

### ISSUE THREAD

**Issue by casett** [benjjneb/decontam#20]
Do you suggest running decontam separate times for different kinds of negative controls or lumping them all together?
I have replicate kit controls, but I also have replicates of different buffers used to surface clean tissues (H20, EtOH, etc). I have tried running decontam both ways (seperately and together) and get different results. My inclination is that it might best to run them seperately??

**Comment by benjjneb** [comment]
If those different negative control types have different spectra of contaminants, it is best to run them separately, but if the contaminants are mostly shared it is best to group them together for more power.

Sorry for the non-simple answer, but the best approach really does depend on that. One way to decide would be to look at the overlap between the top features found in the different control types.

**Comment by casett** [comment]
Thanks! That is what I was thinking as well.
