### ISSUE TITLE
Subtract prevalence values from samples?

### ISSUE THREAD

**Issue by rachaelantwis** [benjjneb/decontam#21]
Hello,
thanks for this great package and tutorial. We have used the prevalence function to create a matrix of sample_sums in the negative controls as follows:

```
ps.neg <- prune_samples(sample_data(ps.NoPosF)$samplecontrol == "NEG", ps.NoPosF)
ps.neg.presence <- transform_sample_counts(ps.neg, function(abund) 1*(abund>0))
prevalence.neg=taxa_sums(ps.neg.presence)
```

We don't want to loose these OTUs if they are real, but also want to remove contaminants. Is it possible to subtract these sample sums (rather than strip out whole OTUs) from the sample data? 

Many thanks in advance

**Comment by benjjneb** [comment]
I don't really understand the goal here. It seems like you are summing up the number of negative control samples in which each OTU appears. What does subtracting that value from the abundances in the real samples accomplish? It's a subtraction of two differents kinds of numbers to start with, subtracting a # of samples from a # of reads.

Our recommendation is that taxa identified as contaminants should be removed, but feel free to elaborate a bit more on what you're aiming to do if I didn't understand it correctly.

**Comment by rachaelantwis** [comment]
Ah sorry, no, this is me being confused! Apologies for that. In that case, is it possible to count up the number of reads of each OTU/SV in the negatives and subtract these from the samples, rather than removing complete OTUs? Many thanks

**Comment by benjjneb** [comment]
> is it possible to count up the number of reads of each OTU/SV in the negatives and subtract these from the samples, rather than removing complete OTUs?

That is not what we recommend. We think that if you identify an OTU/ASV that is primarily a contaminant (which decontam is trying to do) it should be removed from your dataset.

That said, you can accomplish any data manipulation you want in R, and what you describe -- subtracting the average abundance in negative controls -- is something people have done before. The way to do that would be via matrix commands on the sequence table.

**Comment by rachaelantwis** [comment]
Ok thank you.
