### ISSUE TITLE
Install in R session

### ISSUE THREAD

**Issue by johnchase** [benjjneb/decontam#22]
Posting if anyone else runs into this issue. Feel free to close.

Attempting to install on linux Ubuntu 16.04.4 LTS

```R
library(devtools)
devtools::install_github("benjjneb/decontam")
Downloading GitHub repo benjjneb/decontam@master
from URL https://api.github.com/repos/benjjneb/decontam/zipball/master
Installation failed: error in running command
```

The following works:
```R
devtools::install_git("git://github.com/benjjneb/decontam",  branch = "master")
```
I am not hugely familiar with R so I'm not sure why the second command works and the first one did not.

**Comment by benjjneb** [comment]
Mysterious!
