### ISSUE TITLE
Using decontam to adjust taxonomic abundances based on taxa present in negative control

### ISSUE THREAD

**Issue by smalanmul** [benjjneb/decontam#23]
I am new to the field of gut microbiome data analysis. I did 16S rRNA seq (V4 region) for DNA extracted from human stool samples. I saw that there were close to 24 000 reads present in my negative control.  I want to know if I can use decontam on my dataset to rectify this contamination issue. I suspect it comes from the library pre, seeing as the Bioanalyzer showed 0ng/ul DNA present in my neg ctrl sample, and the composition of the neg ctrl is not typical of stool microbiota. The most abundant taxa were Sediminibacterium (12 487 reads) and Phyllobacterium (3 637 reads), but there are also taxa that are usually quite abundant in gut microbiome data sets, such as Prevotella and Bacteroides, that were present in this negative sample. Therefore, I do not merely want to remove these taxa from all samples, as this will not be an accurate representation of the true gut microbial composition. I was wondering whether decontam addresses this problem, from the paper on bioRxiv it seems like it does, but I am unsure of the script performing this correction/removal step. I went through the tutorial online, but I am unsure of what script to use to do the actual removal/counts correction based on taxa present in the negative control. I would appreciate any feedback, thanks.

**Comment by benjjneb** [comment]
Hi,
In the tutorial the line used to remove the taxa identified as contaminants was this one:

```
ps.noncontam <- prune_taxa(!contamdf.freq$contaminant, ps)
```

You would use bascially the same command after running prevalence-based identification on your phyloseq object, or if you are working directly with the sequence table as a matrix, you can just remove columns that were identified as contaminants, e.g. `seqtab.noncontam <- seqtab[,!contamdf$contaminant)]`

> The most abundant taxa were Sediminibacterium (12 487 reads) and Phyllobacterium (3 637 reads), but there are also taxa that are usually quite abundant in gut microbiome data sets, such as Prevotella and Bacteroides, that were present in this negative sample. Therefore, I do not merely want to remove these taxa from all samples, as this will not be an accurate representation of the true gut microbial composition. I was wondering whether decontam addresses this problem,

Absolutely, this was one of the motivations for creating decontam. The prevalence method will not flag taxa as contaminants just because they are in your negative controls. They have to be _more prevalent_ in the negative controls than in the true sample to get flagged (i.e. present in a higher fraction of samples). Thus those abundant and true cross-contaminants shouldn't be flagged and won't be removed.

**Comment by smalanmul** [comment]
Thanks very much, this is very helpful! I recently had a colleague with concerns about using decontam, and her concern as that sequencing data is compositional and that the proportion of reads from contaminants also affect the number of reads of other taxa. There probably isn't any way of getting around that particular issue is there?

**Comment by smalanmul** [comment]
Hi

So do you think I should use the prevalence method rather for my data?

Kind regards
Stefanie

**Comment by smalanmul** [comment]
Hi

So based on what you stated above (The prevalence method will not flag taxa as contaminants just because they are in your negative controls. They have to be more prevalent in the negative controls than in the true sample to get flagged (i.e. present in a higher fraction of samples). Thus those abundant and true cross-contaminants shouldn't be flagged and won't be removed.) - should I rather use the prevalence method? 
Then for the prevalence method - how do I remove the contaminating taxa from the phyloseq object? Is it similar to the frequency method, thus based on tutorial: ps.noncontam <- prune_taxa(!contamdf.prev05$contaminant, ps)

Thanks for your help!

**Comment by benjjneb** [comment]
> So based on what you stated above (The prevalence method will not flag taxa as contaminants just because they are in your negative controls. They have to be more prevalent in the negative controls than in the true sample to get flagged (i.e. present in a higher fraction of samples). Thus those abundant and true cross-contaminants shouldn't be flagged and won't be removed.) - should I rather use the prevalence method?

Sure. I think the frequency method would also work for your data, but the prevalence method is fine on its own.

> Then for the prevalence method - how do I remove the contaminating taxa from the phyloseq object? Is it similar to the frequency method, thus based on tutorial: ps.noncontam <- prune_taxa(!contamdf.prev05$contaminant, ps)

Yep, will work just the same.
