### ISSUE TITLE
error using isContaminant using prevalence and defining batch

### ISSUE THREAD

**Issue by RimaChakaroun** [benjjneb/decontam#27]
Hey @benjjneb , 

thanks for this pretty user friendly and yet super important package. 
I'm running into an error trying to use prevalence to filter contaminant sequences when I use the argument batch. 
`contamdf.prev <- isContaminant(ps1, method = "prevalence", neg = "is.neg", threshold = 0.1 , batch = "extraction_batch")`

the error I get:

> Error in apply(seqtab[batch == bat, ], 2, isContaminantPrevalence, neg = neg[batch ==  : 
  dim(X) must have a positive length

I initially had names and numbers as levels for the factor variables batch_extraction and thought this was confusing and simply turned it into integers , but that did not seem to solve the problem. There are also no NAs in there .

`levels(sample_data(ps1)$extraction_batch)`

> [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15" "16"

`sum(is.na(sample_data(ps1)$extraction_batch))`

> [1]0

Thanks for the help!

R

**Comment by benjjneb** [comment]
What is the output from the following?

```
samdf <- as(sample_data(ps), "data.frame")
table(samdf$batch, samdf$is.neg)
```

**Comment by RimaChakaroun** [comment]
Hey , 

`table(sample_data(ps1)$is.neg , sample_data(ps1)$extraction_batch)`
  
  gives me the following output (the same output I get running the command you suggested)
 

```
                1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16
  FALSE 13  0  0 20 17 18 14 34 19 20 42 72  4  0 14  5
  TRUE   1  1  1  1  2  1  1  2  1  1  2  9  0 15  0  0
```

thanks!

**Comment by benjjneb** [comment]
The error is being triggered by some of the batches only have one sample in them. This should probably be caught and handled more gracefully so I am tagging this issue as enhancement.

However, I would suggest that splitting these up by batch might not be the best way to go. The prevalence method really starts working when you have multiple negative controls (in our revised preprint we suggest 5+) and in all but one of two of these batches there are 2 or less negative controls.

I think your best bet here is probably to group everything together for use with the prevalence method. If you were using the same protocols and kits in each batch, this should be a reasonable thing to do.

**Comment by RimaChakaroun** [comment]
Thanks for this, I ended up putting all of my negative samples together and it works out fine. My mistake is that for sequencing I pooled the 4 negative samples I amplified. I ll note this for the next time. 
Thanks again!

**Comment by benjjneb** [comment]
@sdp88 It probably still makes some sense, in that just using the `frequency` method rather than the `combined` method might work better if the number of controls is less than 5. But I would think that as long as the number of controls was >2 that `combined` would add something...

We haven't tested that comparison at low n_control though. Perhaps the best approach would be to try both, plot the distribution of scores, and see if one is more clearly bimodal. If you see something interesting, we'd love to hear about it!
