### ISSUE TITLE
Contaminants sequence order

### ISSUE THREAD

**Issue by sfeds** [benjjneb/decontam#48]
Hi Ben,

I'm analyzing a set of (should be) low density samples, so I'm very keen on using decontam on these. I had the impression from using the package before, that the list of decontam sequences matched my ASV numbers. Is this true or was it never the case?

This is not how I get it now, as seen here:
> head(which(contamdf.freq$contaminant))
[1]   1 116 131 205 257 295

> head(contamdf.freq)
                freq prev     p.freq p.prev          p contaminant
ASV685  6.634510e-06    3 0.04534626     NA 0.04534626        TRUE
ASV909  6.115685e-06    2 0.44257891     NA 0.44257891       FALSE
ASV3435 8.417406e-08    1         NA     NA         NA       FALSE
ASV3639 9.660290e-08    1         NA     NA         NA       FALSE
ASV3384 1.445301e-07    1         NA     NA         NA       FALSE
ASV2544 3.857240e-06    1         NA     NA         NA       FALSE

Where contaminant sequence "1" is then "ASV685".

I guess this is not a big of an issue, but somehow the number of the contaminating sequence helped in the process of selecting thresholds etc., depending on their rarity.
I'm using 
R version 3.5.1 (2018-07-02)
> library(decontam); packageVersion("decontam")
[1] ‘1.2.0’

Thanks

**Comment by benjjneb** [comment]
If you are using the phyloseq objects as intermediates, then we can't guarantee ASV order will remain the same. If you want that, you should work directly with the sequence table.

But in any case, you should be able to use the names that you've given these sequences (e.g. "ASV685") to get back the information you want, perhaps by extracting the number from the name, `as.integer(gsub("ASV", "", asv.name))`.

**Comment by sfeds** [comment]
Hi Ben,
I get it, however I always work with phyloseq as intermediate (I wouldn't know how to use the function with independent tables :) )
But I have now used your input to create:

contaminants <- as.integer(gsub("ASV", "", rownames(contamdf.freq, contamdf.freq$contaminant==TRUE)))

which gives me the ASV number. True, I could also just call the rownames for that.

Ok, thanks, good to know it's ok that which(contamdf.freq$contaminant) and ASV numbers don't necessarily need to match.

**Comment by sfeds** [comment]
Ah wait, I might have said victory too early... it seems like I don't only get the true contaminants like that.
Any tips? (apologies for my limited coding skills...)

**Comment by sfeds** [comment]
And if it's ok, a more phylosophical question: is it ok to get a "gut feeling" on wheather a sequence is a true contaminant or not based on the number of ASV? I had the impression that, the higher the number, the "rarer" the sequence, therefore higher the chances of it being contaminating. 
Thanks!!

**Comment by benjjneb** [comment]
> And if it's ok, a more phylosophical question: is it ok to get a "gut feeling" on wheather a sequence is a true contaminant or not based on the number of ASV? I had the impression that, the higher the number, the "rarer" the sequence, therefore higher the chances of it being contaminating.

I think it's fair to look more closely at highly abundant ASVs that are called contaminants, to double-check they really are contaminants. Most contaminants (outside of really low biomass samples) do show up in the rarer fraction, but not all.

I wouldn't make too much of it though. I'd recommend the `plot_frequency` function we added to decontam as a way to visualize the distribution across samples yourself as another way to inspect potential contaminants of high interest.
