### ISSUE TITLE
Documentation for preparing or cleaning input data

### ISSUE THREAD

**Issue by lakarstens** [benjjneb/decontam#5]
There are a few warnings or errors that occur if the input data is not cleaned prior to running decontam in the isContaminant function: 

If there are samples with no reads, the error that occurs is: 
**Error in if (sum(freq > 0) > 1) { : missing value where TRUE/FALSE needed**

This is easily fixed by filtering out low/zero read samples with phyloseq subset_samples. The vignette decontam_intro.Rmd states to keep low read samples, it might be good to suggest a lower limit (0 reads is a bit obvious, but would a sample with only 100 reads be meaningful?). 

If there are zeros in the conc variable, the error that occurs is:
**Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  NA/NaN/Inf in 'y'**

If there are negative values in the conc variable, the warning that occurs is:
**In log(conc) : NaNs produced**
Which then produces an error later on when running plot_abundance:
**Error in plot_abundance(ps, taxa_names(ps)[c(1, 3)], conc = "DNA_conc") : 
  conc must be positive numeric.**

These can be prevented by adding documentation recommending that the user handles negative/zero values in the conc variable. It might be good to incorporate error handling on the variable that is passed as conc in isContaminant and to print an message to the user to check their data if it contains negative/zero/or NaNs.

**Comment by benjjneb** [comment]
Both should be fixed in 87c92dec6f62279a567a3dc2f3f7917e662baa9f

Zero-read samples are now ignored by the "frequency" method, and the `conc` vector is now appropriately checked upon input and required to be a positive numeric.
