### ISSUE TITLE
input matrix

### ISSUE THREAD

**Issue by biocoreexpert** [benjjneb/decontam#54]
Hi,
I have an expression data frame with rows=samples and columns=bacterial_species. The data frame has been generated using kraken.  Can I use this as input? 

          p__Acidobacteria p__Caldiserica p__Elusimicrobia
     D1_S1               58             41              289
     D2_S2               59             46              326

**Comment by benjjneb** [comment]
Yes,  but `isContaminant` expects a matrix data type, so convert the data.frame to a matrix first.

```
species.table <- as(species.df, "matrix")
```

**Comment by biocoreexpert** [comment]
[   DNA_conc d__Viruses d__Bacteria d__Eukaryota k__Fungi
D1        5         11     2933770          428      164
D2        5         24     3314330          525      197
D3        5          9     3550188          521      220](url)

**Comment by benjjneb** [comment]
The DNA_conc should be provided as a stand-alone vector, not mixed into the species table.

From what you have, you can assign that column to its own vector, remove it from the table, and then it should run as expected. Something like this:

```
conc.vec <- species.table[,1]
species.table <- species.table[,-1] # Remove first column
contam.freq <- isContaminant(species.table, method="frequency", threshold=0.1, conc=conc.vec)
```

**Comment by biocoreexpert** [comment]
thanks
