### ISSUE TITLE
plotting contaminant frequencies and sample dna concentrations for multiple otus

### ISSUE THREAD

**Issue by mmvivaldi** [benjjneb/decontam#65]
I have processed a feature table to identify contaminants with iscontaminant in an R environment. After obtaining the list of contaminants I want to plot their frequencies against the dna concentration of samples, but the number of contaminants is too high to include them as facets of a complex graph (300 assigned contaminants out of 5400 otus considered). I would like to run the plotting of the different otus independently but I haven´t been successful in applying the function plot.frequency in a recurrent way to a list of otus using loops. Indeed I have even been unable to call the otu names in the second argument of the function taking them from a variable in a data table or vector, only when I have directly written them within the correct position of the argument as a comma separated list or a c() combination of names has it worked correctly. In the examples provided in decontam_intro.html for phyloseq objects, the names of otus are called with the taxa_names() function, my first question is if this can only be made using phyloseq objects or I can do it in R with my data sets imported from Qiime2 or csv formats (i.e. the function depend on phyloseq packages in any way?) I am only an occasional R user, and am not expert in the use of commands to perform iterations of the same task in a list taken from variables in a table, but also wonder whether when the argument is identified by position in the list of the function (as the name of OTUS for plot.frequency) iteration of the function for i values in that position is possible and how could it be written. Can the problem come from the use of an external source for the call of contaminants by their name? (a vector only with the names of the contaminants extracted from the original feature table, I am thinking whether the invisible recoding of names to numbers by R could make unrecognizing them as the same names within the feature table). I would appreciate any help in this task.
Additionally, I would like to see the types of samples as points of different color in the plot. I know this can be made for those identified as negative controls with the argument neg. I wonder whether it is possible to include arguments to use a factor with more than two levels for that purpose, otherwise I would use the neg argument with different variables assigned (one for each kind of sample always as a logic class) in different runs for the same otu and work with as many plots as kinds of samples for each OTU. Probably there are several easier ways to do that... hope somebody can help with this.
Thank you very much in advance for your help
Manuel MV

**Comment by mmvivaldi** [comment]
Dear Benjamin Callahan,

I complete my previous comment by, first of all, thanking you for the development of this very useful tool (I am quite new in this kind of forums and didn´t realize I was really writing mainly to you). 
Second I have been trying to get the 300 independent plots automatically through two ways, iteration of the generation of plots, but also p.list=lapply for separating facets after generation of a composed plot, but can´t find the right syntaxis. My questions posted in the first comment stay unresolved, despite I have tried to call the otu names from the same data.frame obtained after running the iscontaminant function.
Thanks in advance for your help.
Manuel MV

**Comment by benjjneb** [comment]
Hi Manuel,
Can you provide the exact commands you are executing that aren't working as desired? Especially the function being called to plot individal OTUs within the loop or lapply.

**Comment by mmvivaldi** [comment]
Hi,
I have ended up performing the graphs manually including 9 plots per window and repeating them assigning different logic variables to neg in order to view the position of the different kind of samples I have. In any case it would be a good idea to know how to do that in a more straight way.
My attempts were: 

FIRST to call the contaminants to plot with the function taxa_names following one of your examples, but R didn´t found the chain "taxa_names" as a valid function

CONTAMINANT.IDENTIFIER.either.perbatch.CONC0.1 <- isContaminant(transposed_calaos_prevmayor4.sinnegPCR2, normalize=TRUE, detailed=TRUE, conc=conc, neg=neg, batch=batch, method=“frequency”)

plot_frequency(transposed_calaos_prevmayor4.sinnegPCR2,taxa_names(CONTAMINANT.IDENTIFIER.either.perbatch.CONC0.1)[c(1,3)], conc=conc, neg = neg, normalize = TRUE, showModels = TRUE, log = TRUE, facet = TRUE)

**Comment by mmvivaldi** [comment]
SECOND I tried to make a loop with FOR, I tried to get a vector with the names of the OTUs identified as contaminants, but it became numeric, I have then extracted the names as a list, but when I try to use the list (even without looping), iscontaminant does not identify it as a valid argument

<list_contaminant<-list(CONTAMINANT.IDENTIFIER.either.perbatch.CONC0.1[, "taxa_name"])
<plot_frequency(transposed_calaos_prevmayor4.sinnegPCR2,list_contaminant, conc=conc, neg = neg, normalize = TRUE, showModels = TRUE, log = TRUE, facet = TRUE)
Error in plot_frequency(transposed_calaos_prevmayor4.sinnegPCR2, list_contaminant,  : 
  taxa must be a vector of taxa names.

Noting that the program indicate that the argument "taxa" is not correct, I have tried indicating taxa=list_contaminant, however the error stays:

> plot_frequency(transposed_calaos_prevmayor4.sinnegPCR2,taxa=list_contaminant, conc=conc, neg = neg, normalize = TRUE, showModels = TRUE, log = TRUE, facet = TRUE)
Error in plot_frequency(transposed_calaos_prevmayor4.sinnegPCR2, taxa = list_contaminant,  : 
  taxa must be a vector of taxa names.

However, when I have called an only OTU with taxa="otuname" it has worked!!

**Comment by mmvivaldi** [comment]
Now I know how to call for otunames in the function, although it seems a list cannot be used as a vector, let´s see if I am able to perform the loop

**Comment by mmvivaldi** [comment]
I have tried this without success:
> for (i in list_contaminant) {plot_frequency(transposed_calaos_prevmayor4.sinnegPCR2,taxa=(CONTAMINANT.IDENTIFIER.either.perbatch.CONC0.1$taxa_names==i), conc=conc, neg = neg, normalize = TRUE, showModels = TRUE, log = TRUE, facet = TRUE)}
Error in plot_frequency(transposed_calaos_prevmayor4.sinnegPCR2, taxa = (CONTAMINANT.IDENTIFIER.either.perbatch.CONC0.1$taxa_names ==  : 
  taxa must be a vector of taxa names.

**Comment by mmvivaldi** [comment]
Trying to call in taxa= for expressions like those you use in your examples give me errors, for example when including [], I do not know how should them be quoted if any:> >plot_frequency(transposed_calaos_prevmayor4.sinnegPCR2,taxa=[sample(which(CONTAMINANT.IDENTIFIER.either.perbatch.CONC0.1$contaminant),3)], conc=conc, neg = neg, normalize = TRUE, showModels = TRUE, log = TRUE, facet = TRUE)
Error: inesperado '[' in "plot_frequency(transposed_calaos_prevmayor4.sinnegPCR2,taxa=["

When I tried with lapply after generating a group of plots, I was also unable to find the right expression, probably I am making some basic errors of sintaxis that make R not recognizing what I intend to call, as probably is happening here within the "taxa" argument.

**Comment by benjjneb** [comment]
From what you are writing, it is likely you are making basic R syntax errors. One solution would be to reach out to someone locally who could sit with you and work through those syntax errors. It would probably be fixable quite quickly.

Alternatively, we can try to help you, but you have to be able to provide complete descriptions of the commands you are trying and how they are failing. Your posts above aren't reaching that level.

**Comment by mmvivaldi** [comment]
Ok, thank you, I will try with somebody here. I copied the commands used for the loop although my long file names and the error answers by R in Spanish probably made the commands hard to understand. 
I will work my basic R a bit further...
Thank you anyway.
Manuel
