### ISSUE TITLE
Quant values to be used: assay or stock calculation(QuBit)?

### ISSUE THREAD

**Issue by emilyjunkins** [benjjneb/decontam#67]
Hello,

Like many folks, I quantify my barcoded samples with Qubit prior to pooling. Qubit generates a value for that assay, but it also allows you to calculate the stock. I wanted to double check that the values needed for the decontam input are those from the assay reading, not the overall stock concentration, or does it matter?

Thanks!

**Comment by benjjneb** [comment]
TBH I'm not sure what the stock reading is that you are referring to.

Which measurement are you using to pool the samples into equimolar concentrations in the sequencer? That is the measurement to use, as it should reflect the concentration of DNA in the sample.

**Comment by emilyjunkins** [comment]
By "stock" I mean when you calculate what is in your total sample based on the assay tube reading (QuBit does that for you). I wanted to make sure I needed to use that number (which is the one used to pool samples). Thanks!
