### ISSUE TITLE
Choice of threshold

### ISSUE THREAD

**Issue by jw51** [benjjneb/decontam#68]
How should you decide a threshold (for the frequency method) if your score histogram is not bimodal. My graph increases more or less linearly between 0 and 0.5 and stays more or less at the 0.5 level between 0.5 and 1... Does this mean this method is not suitable for my data? I only have three negative controls, so the prevalence method alone is probably not sufficient...

**Comment by benjjneb** [comment]
If there is no evidence of bimodality, it either suggests that the model for contaminants/non-contaminants is not effective in your dataset, or that you just don't have enough information in your data to effectively discriminate some of the contaminants from the non-contaminants. How many samples are you using in the frequency method? What is the distribution of dna concentrations of your samples? Do your samples mostly of a single sample type, or are they a mixture of different sample types?

**Comment by benjjneb** [comment]
> How should you decide a threshold (for the frequency method) if your score histogram is not bimodal.

If your goal is primarily to remove the most obvious contaminants (conservative contaminant removal) then I would pick a threshold that removes the low score tail, as the lower the score the stronger the fit between the contaminant model and that OTU/ASV (relative to the non-contaminant model).

**Comment by jw51** [comment]
I have 200 samples included (all fecal samples). DNA concentrations are a bit right/positive skewed. Yes, I would at least want to remove obvious contaminants. So if I would set my threshold rather low (0.01 for example), I would remove the most important contaminants? Or shouldn't I interpret it that way if the distribution is not bimodal and only rely on the prevalence method (even if I only have 3 negative controls)?

**Comment by benjjneb** [comment]
> I have 200 samples included (all fecal samples). DNA concentrations are a bit right/positive skewed

That sounds good. Skewed DNA concentrations are expected, you just want there to be a decent range of them, at least a 2-fold range and more range is better.

> So if I would set my threshold rather low (0.01 for example), I would remove the most important contaminants? Or shouldn't I interpret it that way if the distribution is not bimodal and only rely on the prevalence method (even if I only have 3 negative controls)?

Given the small number of controls, I would try using the frequency information. It is not obvious that the smallest scores will be the "most important" contaminants though. They might be but one diagnostic worth plotting is score, or perhaps log score, vs. total abundance across the data set.

The "most important" contaminants are those that are more abundant/prevalent typically, as they will be the ones that interfere the most in subsequent analysis.

**Comment by jw51** [comment]
I have a more than 2-fold range in DNA concentrations. Most of my sequences with low scores (< 0.1) have a very low total abundance (and low prevalence: less than 10 samples). So I probably can't do much harm removing them, but it won't have a big effect if I don't?

**Comment by benjjneb** [comment]
> I have a more than 2-fold range in DNA concentrations. Most of my sequences with low scores (< 0.1) have a very low total abundance (and low prevalence: less than 10 samples). So I probably can't do much harm removing them, but it won't have a big effect if I don't?

Yeah that's probably about right. 

To be honest, I think the patterns you are seeing are indicating that you don't have much contamination in your samples - a good thing! It's also not too surprising (assuming decent wet lab practices): fecal samples have very high microbial concentrations, and so any contamination is usually overwhelmed by the legitimate sample DNA. Samples with lower microbial concentrations are the ones that tend to have bigger contamination problems.

**Comment by jw51** [comment]
That's good to hear! Thank you for your (quick!) advice!
