### ISSUE TITLE
isContaminant produces all NaN, due to zero-read sample

### ISSUE THREAD

**Issue by roey-angel** [benjjneb/decontam#7]
I'm trying out decontam on a pretty standard MiSeq dataset, processed with DADA2.
Running:
```{r}
contamdf.freq <-
  isContaminant(ps, method = "frequency", conc = "ng.pooled")
print(contamdf.freq)
```
Gives me:

```{r}
         freq prev p.freq p.prev  p contaminant
Seq_1     NaN   NA     NA     NA NA       FALSE
Seq_2     NaN   NA     NA     NA NA       FALSE
Seq_3     NaN   NA     NA     NA NA       FALSE
...
```
And running:

```{r}
plot_frequency(ps, taxa_names(Evrona)[c(1,3)], conc = "ng.pooled")
```

Gives:

```{r}
Error in if (sum(freq > 0) > 1) { : missing value where TRUE/FALSE needed
```

Although all taxa have a total abundance above 0
```{r}
ps %>% taxa_sums() %>% as.data.frame() %>% filter( . > 0) %>% nrow/ntaxa(ps)
[1] 1
```

This is what my phyloseq object looks like:
```{r}
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1842 taxa and 110 samples ]
sample_data() Sample Data:       [ 110 samples by 8 sample variables ]
```
My concentration information is called `ng.pooled` and looks like this (because we try to normalise input quantity)
```{r}
ps %>% sample_data() %>% .$ng.pooled
  [1] 1.3 6.9 6.9 1.1 6.9 6.9 4.1 6.9 6.9 6.9 6.9 6.9 3.7 2.8 6.9 6.9 6.9 6.9 6.9 6.9 6.9
 [22] 6.9 2.0 6.9 2.4 1.1 2.0 6.9 6.9 6.9 6.9 6.9 0.7 6.9 6.9 6.9 4.6 6.9 6.9 6.9 6.0 6.9
 [43] 6.9 6.9 6.9 6.9 4.8 1.6 0.9 0.3 0.3 6.9 6.9 1.8 6.9 6.9 6.9 4.4 6.9 6.9 6.7 6.9 6.9
 [64] 6.9 6.9 6.9 6.9 6.9 6.9 6.9 6.9 6.9 6.9 6.9 6.9 6.9 5.9 6.9 4.4 5.3 6.9 6.9 6.9 6.9
 [85] 6.9 6.9 3.8 6.9 6.9 5.9 6.7 6.9 6.9 6.9 6.9 6.9 6.9 6.9 6.9 6.9 6.9 5.0 3.8 4.8 4.2
[106] 6.9 6.9 6.9 6.9 6.9
```

Is it not working because my concentration are so similar? Or is there another reason?

**Comment by benjjneb** [comment]
The concentrations are all positive and non-zero, so that shouldn't be driving the NaNs...

My first guess is that you have a sample with zero reads in it in your phyloseq object. Another possibility is that you have a taxa with zero reads (although I don't think that would cause this).

Can you try the following:
```{r}
summary(sample_sums(ps))
summary(taxa_sums(ps))
```

If there are zero-read samples, then you could try running `isContaminant` again after removing them. If it's not that, could you share the phyloseq object (or a stripped down version) that causes this error?

**Comment by roey-angel** [comment]
Indeed, one of the control samples had zero counts.
I missed out on that and honestly, didn't think this would cause issues.

**Comment by benjjneb** [comment]
Re-opening, because this should be handled more gracefully.

**Comment by roey-angel** [comment]
I've also now realised that I used the conc. post-pooling instead of pre-pooling, but that's a different story...

**Comment by sarasary82** [comment]
Hi benjineb, I get same error message:

x_freq <- isContaminant(as.matrix(s_no_freq[,1:376]), method="frequency", conc="quant_reading")
Error in isContaminant(as.matrix(s_no_freq[, 1:376]), method = "frequency",  : 
  conc must be positive numeric

but my concentrations aren't 0, and also I have neither sample with zero reads nor taxa with zero reads.. (of course I have many features that are 0 but this is not a problem right?) what could then be?
Thank you for your help!

**Comment by benjjneb** [comment]
You aren't providing a phyloseq object, so you need to provide a vector of the quantitative readings to the `conc` argument, rather than a variable name.

See the description of the `conc` argument in `?isContaminant`
