### ISSUE TITLE
Specifying multiple confounders for batch parameter

### ISSUE THREAD

**Issue by cdeanj** [benjjneb/decontam#73]
Hi Dr. Callahan,

The decontam tutorial and R documentation mention the possibility of controlling for putative batch effects via the _isContaminant_ function, using the **batch** parameter.

Is it possible to control for multiple confounders using this parameter (e.g., sequencing run and extraction kit)?

I tried to do this using the tutorial data in the following way:
```
ps <- readRDS(system.file("extdata", "MUClite.rds", package="decontam"))
sample_data(ps)$Kit <- sample_data(ps)$Kit <- sample(x = c("PowerFood", "PowerSoil"), prob = c(.5, .5), size = 569, replace = TRUE)
sample_data(ps)$Run <- sample_data(ps)$Run <- sample(x = c("First", "Second"), prob = c(.5, .5), size = 569, replace = TRUE)
contamdf.freq <- isContaminant(ps, method="frequency", conc="quant_reading", batch = c("Kit", "Run"))
```
But received an error:
```
Error in isContaminant(ps, method = "frequency", conc = "quant_reading",  : 
  The length of batch must match the number of samples (the rows of seqtab).
```
I don't think that differing extraction methods would violate the main assumption of the frequency-based model (i.e., contaminating DNA present in uniform concentration across samples), even if one method was optimized in such a way to reduce it.

To be safe, I suppose I could stratify the phyloseq object by extraction method and run decontam separately on each subset and then merge results.

Just curious if specifying multiple confounders is possible and what effects differing extraction methods might have on the model assumptions.

Thanks!
Chris

**Comment by benjjneb** [comment]
> Is it possible to control for multiple confounders using this parameter (e.g., sequencing run and extraction kit)?

First I should clarify, the batch option in `isContaminant` is not truly "controlling for confounders" in the sense of incoporating them into a full-dataset statistical model. Rather, it is just operating the core algorithm on each batch fully independently, and then making a consensus choice on whether something is called a contaminant or not based on the most extreme score.

So, in the truest sense (I think) of what you are asking, the answer is no. However, in the limited sense in which `isContaminant` is controlling for batch, the answer is yes, by augmenting your phyloseq object with a composite `Kit_and_Run` metadata column, and then providing that as the `batch` argument.
