### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by apchumangenomics** [benjjneb/decontam#8]
To whom it may concern,

I am just going through your sample data and I am running into a problem at the initial stages.

When trying to create the object 'ps' I am receiving a error as below

Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '', probable reason 'Invalid argument'
All versions of relevant packages are up to date, 

I am not sure of the origin of this problem. One suggestion was that the relevant sample files were not available. 

Thanks for any help.

All the best,
Maurice

**Comment by benjjneb** [comment]
Can you clarify what exact command you are running to cause that error? Is this from running the vignette?

**Comment by benjjneb** [comment]
Ah, found the bug. If you reinstall from github, the updated package version should work as expected, i.e. `ps <- readRDS(system.file("extdata", "MUClite.rds", package="decontam"))` will work.

Thanks for letting us know!
