### ISSUE TITLE
2x2 presence/absence table 

### ISSUE THREAD

**Issue by younjungkim0513** [benjjneb/decontam#86]
May I ask you how a 2 × 2 presence-absence table is created for a given ASV? 

My understanding is that it is different from a 2 x 2 contingency table that we use to assess the association between two variables with chi-square statistics? It does not seem possible to create a 2 x 2 contingency table because we are dealing with prevalence in different sample types (true and control samples), not two variables. 

What does each column (or row) represent in the 2 × 2 presence-absence table? For example, if a given ASV appeared in 12 out of 117 true samples, and 5 out of 13 control samples, how would the table look like? 

Best regards,

Younjung

**Comment by benjjneb** [comment]
For the `"prevalence" method it is a presence'absence table. So, if reads great then TRUE, else FALSE.

**Comment by younjungkim0513** [comment]
Sorry, I do not understand. How could it be a "2 x 2" table, then? The following is the format I can imagine. 
Each element in the table needs to be the number of true samples (i) with that ASV, (ii) without that ASV, the number of controls (iii) with that ASV, or (iv) without that ASV. 

Best,

Younjung

**Comment by younjungkim0513** [comment]
I got it from your source code. It is based on a chi-square p-value by comparing two proportions. I misunderstood it as a chi-square test from a 2x2 contingency table. Thanks!!!
